spring.application.name=SDEPro0_12026
spring.datasource.url=jdbc:mysql://localhost:3306/sdepro2026
spring.datasource.username=root
spring.datasource.password=SDEroot_pass1user1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
logging.level.org.springframework.security=TRACE

